name: Checks

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install pandoc
        run: sudo apt-get install pandoc

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        # Caching informed by:
        # https://stackoverflow.com/questions/62977821/how-to-cache-poetry-install-for-github-actions
        # https://github.com/snok/install-poetry
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction

      - run: poetry install
      - run: poetry run ruff .
      - run: poetry run black .
      # - run: poetry run mypy site_builder tests
      - run: poetry run pytest
